openapi: 3.1.0
info:
  title: Task Commander API
  version: 1.0.0
servers:
  - url: https://task-commander-gpt.onrender.com

paths:
  /init_menu:
    get:
      summary: Returns the main Task Commander menu
      operationId: initMenu
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Menu options
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartMenu'

  /get_tasks:
    get:
      summary: Fetch open tasks from Todoist
      operationId: getTasks
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of open tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TasksResponse'

  /complete_task:
    post:
      summary: Mark task as complete in Todoist
      operationId: completeTask
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteTaskInput'
      responses:
        '200':
          description: Confirmation of completion

  /add_task:
    post:
      summary: Add a new task to Todoist
      operationId: addTask
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTaskInput'
      responses:
        '200':
          description: Task created

  /get_projects:
    get:
      summary: Fetch your Todoist projects
      operationId: getProjects
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectsResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    StartMenu:
      type: object
      properties:
        options:
          type: array
          items:
            type: string
          example:
            - top3_focus
            - full_overview
            - complete_task
            - add_task
            - get_projects

    TasksResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            type: object
            properties:
              id:      { type: string }
              content: { type: string }
              due:     { type: string, nullable: true }
              tags:
                type: array
                items: { type: string }

    CompleteTaskInput:
      type: object
      required:
        - task_id
      properties:
        task_id: { type: string }
        comment: { type: string }

    AddTaskInput:
      type: object
      required:
        - content
        - due_string
      properties:
        content:    { type: string }
        due_string: { type: string }
        project_id:
          type: string
          nullable: true
        project_name:
          type: string
          nullable: true

    ProjectsResponse:
      type: object
      properties:
        projects:
          type: array
          items:
            type: object
            properties:
              id:   { type: string }
              name: { type: string }