openapi: 3.1.0
info:
  title: Task Commander API
  version: 1.1.0
servers:
  - url: https://task-commander-gpt.onrender.com

paths:
  /init_menu:
    get:
      summary: Returns the main Task Commander menu
      operationId: initMenu
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Menu options
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartMenu'

  /get_tasks:
    get:
      summary: Fetch open tasks from Todoist
      operationId: getTasks
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 200
          description: Number of tasks to return
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
            minimum: 0
          description: Pagination offset
      responses:
        '200':
          description: List of open tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TasksResponse'

  /complete_task:
    post:
      summary: Mark task as complete in Todoist
      operationId: completeTask
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteTaskInput'
      responses:
        '200':
          description: Confirmation of completion

  /add_task:
    post:
      summary: Add a new task to Todoist
      operationId: addTask
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTaskInput'
      responses:
        '200':
          description: Task created

  /quick_add:
    post:
      summary: Quick Add — nur Task‑Name, landet in Inbox
      operationId: quickAddTask
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuickAddInput'
      responses:
        '200':
          description: Task created in Inbox project

  /update_task:
    patch:
      summary: Update existing task (Due, Duration, Project, Content)
      operationId: updateTask
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskInput'
      responses:
        '200':
          description: Task updated

  /get_projects:
    get:
      summary: Fetch your Todoist projects
      operationId: getProjects
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectsResponse'

  /plan_tasks:
    get:
      summary: Zeigt alle Aufgaben ohne Due/Duration zur Planung
      operationId: planTasks
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Liste der zu planenden Tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TasksResponse'
        
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    StartMenu:
      type: object
      properties:
        options:
          type: array
          items:
            type: string
          example:
            - top3_focus
            - full_overview
            - complete_task
            - add_task
            - quick_add
            - get_projects
            - plan_tasks
            - update_task

    TasksResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              content:
                type: string
              due:
                type: string
                nullable: true
              duration_minutes:
                type: integer
                nullable: true
                description: Estimated effort in minutes
              tags:
                type: array
                items:
                  type: string
              needs_scheduling:
                type: boolean
                description: True, wenn weder due_string noch duration gesetzt sind    
        offset:
          type: integer
          description: Current pagination offset
        limit:
          type: integer
          description: Current pagination limit

    CompleteTaskInput:
      type: object
      required:
        - task_id
      properties:
        task_id:
          type: string
        comment:
          type: string

    AddTaskInput:
      type: object
      required:
        - content
      properties:
        content:
          type: string
        project_id:
          type: string
          nullable: true
        project_name:
          type: string
          nullable: true
        due_string:
          type: string
          nullable: true
          description: A natural‑language due date
        duration_minutes:
          type: integer
          nullable: true
          description: Estimated effort in minutes
      oneOf:
        - required: ["due_string"]
        - required: ["duration_minutes"]
      description: |
        Intake-Regel: Wenn kein due_string angegeben wird, muss duration_minutes gesetzt sein,
        um Eisenhower-Planung & Scheduling zu ermöglichen.

    QuickAddInput:
      type: object
      required:
        - content
      properties:
        content:
          type: string
      description: >
        Quick Add: spontane Einfälle ohne Zeit-/Projektangabe, landen in Inbox.

    UpdateTaskInput:
      type: object
      required:
        - task_id
      properties:
        task_id:
          type: string
        content:
          type: string
          nullable: true
        project_id:
          type: string
          nullable: true
        project_name:
          type: string
          nullable: true
        due_string:
          type: string
          nullable: true
        duration_minutes:
          type: integer
          nullable: true
      description: >
        Ermöglicht nachträgliches Ergänzen/Anpassen von Task-Feldern

    ProjectsResponse:
      type: object
      properties:
        projects:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string